---
- name: Setup Ubuntu VM
  hosts: all
  tasks:
  - name: Remove Docker GPG key if it exists
    file:
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      state: absent
    become: yes
    tags: docker
  
  - name: Add Docker GPG key
    shell: >
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    become: yes
    tags: docker
    
  - name: Set permissions on Docker GPG key
    file:
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      mode: a+rw
    become: yes
    tags: docker
  
  - name: Install Docker repository
    shell: >
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    become: yes
    tags: docker
  
  - name: Update APT cache
    apt: 
      update_cache: yes
    become: yes
    tags: docker
  
  - name: Install Docker packages
    apt:
      pkg: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
    become: yes
    tags: docker